language: node_js

node_js:
  - "8"

install:
  - npx install-peerdeps --dev eslint-config-airbnb
  - npm install
  
script:
  - npm run lint
  - npm test -u

after-script:
  - COVERALLS_REPO_TOKEN=$coveralls_repo_token npm run coveralls